apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atmo-bundle-pvc
  namespace: suborbital
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi